if game.PlaceId == 653205701 then
    local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
    local Window = Library.CreateLib("FortMart ;D", "GrapeTheme")
    local Main = Window:NewTab("Teleportos")
    local Section = Main:NewSection("Teleportos")
    Section:NewButton("Obby", "", function()
     game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(1465.4, 8.9, 871.3)
end)
    Section:NewButton("Cockpit", "", function()
     game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(1367.2, 2137.8, 2557.1)
end)
    Section:NewButton("Skydive station", "", function()
     game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-53.68, 9.6, 1623.6)
end)
    Section:NewButton("Tryouts square", "", function()
     game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(16.07, 9.66, 1320.86)
end)
    Section:NewButton("Gate (civ side)", "", function()
     game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(283.6, 9.5, 371.1)
end)
    Section:NewButton("Gate (mp side)", "", function()
     game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(283.9, 9.5, 446.9)
end)
    Section:NewButton("Wardrobe", "", function()
     game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(77.9, 9.7, 512.6)
end)
local Playa = Window:NewTab("Player")
local Pllaya = Playa:NewSection("Player")
Pllaya:NewSlider("Walkspeed", "", 500, 16, function(s) -- 500 (MaxValue) | 0 (MinValue)
    game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = s
end)
Pllaya:NewSlider("Jumppower", "", 150, 50, function(s) -- 500 (MaxValue) | 0 (MinValue)
    game.Players.LocalPlayer.Character.Humanoid.JumpPower = s
end)
end